/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2022-08-01 08:16:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.hcmuaf.util.SecurityUtils;
import edu.hcmuaf.security.CustomSuccessHandler;
import edu.hcmuaf.util.CartUtil;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("edu.hcmuaf.security.CustomSuccessHandler");
    _jspx_imports_classes.add("edu.hcmuaf.util.SecurityUtils");
    _jspx_imports_classes.add("edu.hcmuaf.util.CartUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark sticky-top\">\r\n");
      out.write("    \t<div class=\"container collapse navbar-collapse px-4 px-lg-5 \">\r\n");
      out.write("        \t<a class=\"navbar-brand\" href=\"<c:url value='/trang-chu' />\">\r\n");
      out.write("        \t\t<i class=\"fa fa-futbol-o\"></i> FOOTBALLFORUS</a>\r\n");
      out.write("        \t\t\r\n");
      out.write("\t        ");
      out.write("\r\n");
      out.write("\t        \t\t\r\n");
      out.write("            <div class=\"collapse navbar-collapse \" id=\"navbarSupportedContent\">\r\n");
      out.write("            \t<ul class=\"navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4 \"></ul>\r\n");
      out.write("                <form class=\"d-flex \">\r\n");
      out.write("                \t<security:authorize access=\"isAuthenticated()\" >\r\n");
      out.write("                \t<!-- data-toggle=\"modal\" \r\n");
      out.write("                    \tdata-target=\"#exampleModalLong\" -->\r\n");
      out.write("                    \t<button class=\"btn btn-outline-light\" type=\"button\" id=\"cart\" >\r\n");
      out.write("\t                    \t<a href=\"<c:url value='/gio-hang' />\" style=\"color: white\">\r\n");
      out.write("\t                    \t\t<i class=\"bi-cart-fill me-1\"></i> DS Xem sau\r\n");
      out.write("\t                    \t</a>\r\n");
      out.write("                        \t<span class=\"badge bg-dark text-white ms-1 rounded-pill\" id=\"cartCounter\">\r\n");
      out.write("                        \t\t");
      out.print(CustomSuccessHandler.count);
      out.write("\r\n");
      out.write("                        \t</span>\r\n");
      out.write("                     \t</button> \r\n");
      out.write("                     </security:authorize>\r\n");
      out.write("                </form>\r\n");
      out.write("               \t<ul class=\"navbar-nav  mb-2 mb-lg-0 ms-lg-4 \">\r\n");
      out.write("                \t<li class=\"nav-item\">\r\n");
      out.write("                       <a class=\"nav-link active\" aria-current=\"page\" href=\"<c:url value='/trang-chu'/>\">Trang chủ</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                        \r\n");
      out.write("                     <security:authorize access=\"isAnonymous()\" >\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"<c:url value='/dang-nhap'/>\">Đăng nhập</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"<c:url value='/dang-nhap/dang-ky' />\">Đăng ký</a></li>\r\n");
      out.write("\t\t\t\t\t</security:authorize>\r\n");
      out.write("                        \r\n");
      out.write("                     <security:authorize access=\"isAuthenticated()\" >\r\n");
      out.write("\t                        <li class=\"nav-item \"><p class=\"nav-link mb-0\" >Welcome, </p></li>\r\n");
      out.write("\t                        <li class=\"nav-item dropdown\">\r\n");
      out.write("\t                             <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t                             \t");
      out.print(SecurityUtils.getPrincipal().getFullName());
      out.write("\r\n");
      out.write("\t                             </a>\r\n");
      out.write("\t                             <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t                                 <li><a class=\"dropdown-item\" href=\"<c:url value='/ho-so' />\">Thông tin</a></li>\r\n");
      out.write("\t                                 <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("\t                                 <li><a class=\"dropdown-item\" href=\"<c:url value='/dang-nhap/quen-mat-khau' />\">Đổi mật khẩu</a></li>\r\n");
      out.write("\t                                 <li><a class=\"dropdown-item\" href=\"<c:url value='/thoat'/>\">Thoát</a></li>\r\n");
      out.write("\t                               </ul>\r\n");
      out.write("\t                        </li>\r\n");
      out.write("                     </security:authorize>\r\n");
      out.write("            \t</ul>  \r\n");
      out.write("        \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<br>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\" navbar navbar-expand-lg navbar-dark bg-secondary  border-bottom-2 border-2 border-secondary\">\r\n");
      out.write("            <div class=\"container collapse navbar-collapse px-4 px-lg-5 \" id=\"navb\">\r\n");
      out.write("                    <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link active ps-0\" aria-current=\"page\" href=\"#!\">Trang chủ</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"<c:url value='/the-loai?categoryCode=nhan-dinh' />\">Nhận định</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"<c:url value='/the-loai?categoryCode=du-doan' />\">Dự đoán</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"<c:url value='/the-loai?categoryCode=chuyen-nhuong' />\">Chuyển nhượng</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"<c:url value='/the-loai?categoryCode=lich-phat-song' />\">Lịch phát sóng</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"<c:url value='/the-loai?categoryCode=khac' />\">Khác</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Thông tin</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#!\">Tất cả</a></li>\r\n");
      out.write("                                <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"<c:url value='/the-loai?categoryCode=cau-thu' />\">Cầu thủ</a></li>\r\n");
      out.write("                                      <li><a class=\"dropdown-item\" href=\"<c:url value='/the-loai?categoryCode=huan-luyen-vien' />\">Huấn luyện viên</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"<c:url value='/the-loai?categoryCode=doi-bong' />\">Đội bóng</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"<c:url value='/the-loai?categoryCode=giai-dau' />\">Giải đấu</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                     <form class=\"form-inline my-2 my-lg-0 d-flex\">\r\n");
      out.write("                        <input class=\"form-control  search\" type=\"text\" placeholder=\"Search...\" id=\"search\">\r\n");
      out.write("                        <!-- <button class=\"btn btn-success my-2 my-sm-0\" type=\"button\">Search</button> -->\r\n");
      out.write("                    </form>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
